cask_args appdir: '/Applications'

tap 'Homebrew/bundle'

brew 'coreutils'
brew 'socat'
brew 'tmux'
brew 'neovim/neovim/neovim'
brew 'node'
brew 'yarn'
brew 'python'	
brew 'jq'
brew 'httpie'

cask 'slack'
cask 'google-chrome'
